### PR TITLE
Mailers

### PR DESCRIPTION
**Pull request by GGadow**
When Player A takes a turn, Player B is sent an email.

### CODE REVIEW

**Comment by GGadow** [comment]
After this failed, I checked locally: I cannot run rake because of some kind of permissions issue with PostgreSQL. Not sure how to fix this.

**Comment by tomun** [comment]
Try rake db:create, the rake db:migrate

**Comment by GGadow** [comment]
Ben:

I have merged Tom's fixes, but I am still getting this error when I run 
rake:

FATAL:  role "ggadow" does not exist (ActiveRecord::NoDatabaseError)

When I try to run rake db:create, I get a similar message about role 
"ggadow" not existing. The app works fine when I run rails server, but I 
cannot do any testing nor is it passing with Travis when I upload it.

Suggestions?

Gregory Gadow
gpg@gregory-gadow.net

**Comment by tomun** [comment]
try
sudo -u postgres createuser --superuser Myname
?
http://stackoverflow.com/questions/23338356/pgconnectionbad-fatal-role-myname-does-not-exist

**Comment by GGadow** [comment]
Ok, I have the superuser set up and can run rake. Two issues:

I cannot, for the life of me, get Postgres to SHUT UP.

I am getting a failure in GamesController#move, specifically

   1) GamesController#move is successful
      Failure/Error: get :move, { id: game.id, row: 0, col: 0 }
      ActiveRecord::RecordNotFound: Couldn't find Player with 'id'=

Putting these failures aside, I have pushed the mailer to your Git repo.

Gregory Gadow
gpg@gregory-gadow.net

**Comment by tomun** [comment]
I can’t figure out the postgres spew either.   the gem ben suggested doesn’t work, has some method not found error.

The #move test is failing because you modified it to call GameMailer#notify_turn, but #notify_turn was passed session[:player_id] for the your_id parameter.    The session hash is blank during tests.

**Comment by tomun** [comment]
I believe the correct fix is to only call the GameMailer.notify_turn if #signed_in? is true and use #current_player instead of accessing the session hash directly.

I’ve made the change and I’ll manually merge the pull request.

**Comment by GGadow** [comment]
Ah! My apologies, I’ll get that fixed right away.

Gregory Gadow

gpg@gregory-gadow.net

**Comment by tomun** [comment]
I already fixed it and merged it into main.

**Pull request merged**
