### PR TITLE
Invitation 2

### PR DESCRIPTION
**Pull request by GGadow**
This seems to be done, but for the life of me, I can't get the two missing tests to work. Testing in the console works, but rake keeps failing.

### CODE REVIEW

**Comment by tomun** [comment]
I can't merge the pull request cuz it's out of date from master.   I think you have to do 'git fetch upstream' followed by 'git rebase master', fix up the conflicts in your editor (search for '===' to find conflicts), commit your conflict resolution changes then 'git push origin your-branch-name'

**Comment by tomun** [comment]
Ok, I manually merged your pull request again.  All tests are passing

**Comment by GGadow** [comment]
I am wanting to add the dashboard, but I'm not sure which is the most 
up-to-date branch. Pulling and merging Master gives me the old version, 
with no code.

Gregory Gadow
gpg@gregory-gadow.net

**Comment by GGadow** [comment]
Feh, disregard that last email, got it now.

Gregory Gadow
gpg@gregory-gadow.net

**Pull request merged**
