### PR TITLE
Invitation

### PR DESCRIPTION
**Pull request by GGadow**
Done for the night, still have a lot of work to do. I have the basic framework for initiating an invitation, but it can't do much until we have the page where players can set their preferences. We also need a page that lists a player's active games, invitations sent out, and invitations received. That should be easy, though.

### CODE REVIEW

**Comment by tomun** [comment]
Thanks Greg.   I merged my branch into master yesterday afternoon that adds
the basic gametype framework and adds a list of available games and
availble players to the static home page if the user is logged in.   It
would be easy to add the list of invites here too.

github can't automatically merge your pull request therefore travis cant
run the tests.   Can you fastforward your local repo (git pull origin
master), resolve the conflicts then push your branch back up?

Thanks!
Tom

**Comment by tomun** [comment]
BTW, I also started changing the Invitation model: i added
#invites_to_player and #invites_from_player methods to Invitation.   I
change the schema slightly so that the "initiating_player"column is now
"player_id" so that there could be belongs_to/has_many relationships
between Player and Invitation.

**Comment by tomun** [comment]
Ok, it took a while, but finally figure out how to manually merged your
pull request from the command line.   You added some new *_spec.rb files
that weren't executing and a mailer that had a syntax error in it.   I
fixed those in the merge.   All tests are now passing or pending, but our
code coverage has gone way down.

The new invite page looks good.   We're at the point where we going to have
to coordinate closely.   What can we work on in parallel?   I can work on
writing tests to get our coverage back up to 100%.    The mailer is failing
when I click on invite.   Do you want to fix that next?

thanks
Tom

**Comment by GGadow** [comment]
Apologies. I now have a merged version and will continue working on the 
invite page. I will get it functioning properly, and code to your tests.

Gregory Gadow
gpg@gregory-gadow.net

**Pull request merged**
